sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - 1.44.0
branches:
  only:
  - master
before_script:
  - (cargo install mdbook --vers 0.4.1 --force || true)
script:
  - mdbook build
  - echo 'nojekyll' > book/.nojekyll
deploy:
  provider: pages
  local-dir: book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
