[book]
title = "Rust 程序设计语言 简体中文版"
authors = ["Steve Klabnik 和 Carol Nichols，以及来自 Rust 社区的贡献（Rust 中文社区翻译）"]
description = "Rust 程序设计语言 简体中文版"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]

[output.latex-pdf]
latex = false
pdf = true
